### ISSUE TITLE
Filter - Component?

### ISSUE THREAD

**Issue by DeanKamali** [yosbelms/react-deco#1]
Hey, 
Thanks for this package, been playing around with it, and if we have Map, why not add Filter? 

```
<Filter target={[1, 2, 3]} condition={(item > 1 ) =>
  <div key={item}>{item}</div>
} />
// prints
2
3
```

**Comment by yosbelms** [comment]
Hey @DeanKamali, I don't understand your proposal. `(item > 1 ) => ` is not a valid JS syntax.
I think a good solution for what you are looking for is to filter data before reach your JSX.
